# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from Cadastro import Cadastro
from Pessoa import Pessoa


class Ui_CADASTRO(object):
    def setupUi(self, CADASTRO):
        CADASTRO.setObjectName("CADASTRO")
        CADASTRO.resize(800, 741)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        CADASTRO.setFont(font)
        self.centralwidget = QtWidgets.QWidget(CADASTRO)
        self.centralwidget.setObjectName("centralwidget")
        self.CadastroFrame = QtWidgets.QFrame(self.centralwidget)
        self.CadastroFrame.setGeometry(QtCore.QRect(50, 40, 711, 251))
        self.CadastroFrame.setMouseTracking(False)
        self.CadastroFrame.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.CadastroFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CadastroFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CadastroFrame.setObjectName("CadastroFrame")
        self.label = QtWidgets.QLabel(self.CadastroFrame)
        self.label.setGeometry(QtCore.QRect(90, 76, 81, 21))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.CadastroFrame)
        self.label_3.setGeometry(QtCore.QRect(90, 160, 101, 21))
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.CadastroFrame)
        self.label_2.setGeometry(QtCore.QRect(90, 120, 101, 21))
        self.label_2.setObjectName("label_2")
        self.cadastrar = QtWidgets.QPushButton(self.CadastroFrame)
        self.cadastrar.setGeometry(QtCore.QRect(310, 190, 91, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.cadastrar.setFont(font)
        self.cadastrar.setStyleSheet("background-color: rgb(51, 209, 122)\n"
"")
        self.cadastrar.setObjectName("cadastrar")
        self.lineEdit = QtWidgets.QLineEdit(self.CadastroFrame)
        self.lineEdit.setGeometry(QtCore.QRect(190, 64, 391, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.CadastroFrame)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 104, 391, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.CadastroFrame)
        self.lineEdit_3.setGeometry(QtCore.QRect(190, 144, 391, 31))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_8 = QtWidgets.QLabel(self.CadastroFrame)
        self.label_8.setGeometry(QtCore.QRect(310, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.MostrarDados = QtWidgets.QFrame(self.centralwidget)
        self.MostrarDados.setGeometry(QtCore.QRect(50, 500, 711, 211))
        self.MostrarDados.setMouseTracking(False)
        self.MostrarDados.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.MostrarDados.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MostrarDados.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MostrarDados.setObjectName("MostrarDados")
        self.label_5 = QtWidgets.QLabel(self.MostrarDados)
        self.label_5.setGeometry(QtCore.QRect(80, 60, 101, 21))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.MostrarDados)
        self.label_4.setGeometry(QtCore.QRect(80, 96, 81, 21))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.MostrarDados)
        self.label_6.setGeometry(QtCore.QRect(80, 140, 101, 21))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.MostrarDados)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 50, 391, 31))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.MostrarDados)
        self.lineEdit_6.setGeometry(QtCore.QRect(180, 90, 391, 31))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.MostrarDados)
        self.lineEdit_7.setGeometry(QtCore.QRect(180, 130, 391, 31))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 300, 711, 191))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.btn_buscar = QtWidgets.QPushButton(self.frame)
        self.btn_buscar.setGeometry(QtCore.QRect(310, 120, 91, 41))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.btn_buscar.setFont(font)
        self.btn_buscar.setStyleSheet("background-color:rgb(249, 240, 107)")
        self.btn_buscar.setObjectName("btn_buscar")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(80, 80, 101, 21))
        self.label_7.setObjectName("label_7")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 64, 391, 31))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(300, 10, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Ubuntu Condensed")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        CADASTRO.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(CADASTRO)
        self.statusbar.setObjectName("statusbar")
        CADASTRO.setStatusBar(self.statusbar)

        self.retranslateUi(CADASTRO)
        QtCore.QMetaObject.connectSlotsByName(CADASTRO)

        self.cad = Cadastro()
        self.cadastrar.clicked.connect(self.btn_Cadastrar)
        self.btn_buscar.clicked.connect(self.btn_Buscar)

    def btn_Cadastrar(self):
        nome = self.lineEdit.text()
        sobrenome = self.lineEdit_2.text()
        cpf = self.lineEdit_3.text()

        if not(nome == '' or sobrenome == '' or cpf == ''):
            pessoa = Pessoa(nome,sobrenome, cpf)
            if (self.cad.cadastrarPessoa(pessoa)):
                QMessageBox.information(None,'AVISO','Cadastro Realizado com Sucesso!!')
                self.lineEdit.setText('')
                self.lineEdit_2.setText('')
                self.lineEdit_3.setText('')
            else:
                QMessageBox.information(None,'AVISO','CPF informado ja existe!')
        else:
                QMessageBox.information(None,'AVISO','Todos os campos devem ser preenchidos!')


    def btn_Buscar(self):
        cpf = self.lineEdit_4.text()
        if not (cpf == ''):
            pessoa = self.cad.buscarPessoa(cpf)
            if(pessoa != None):
                self.lineEdit_5.setText(pessoa.cpf)
                self.lineEdit_6.setText(pessoa.nome)
                self.lineEdit_7.setText(pessoa.sobrenome)
            else:
                QMessageBox.information(None,'AVISO','CPF não cadastrado')
        else:
            QMessageBox.information(None,'AVISO','Necessário o cpf')


    def retranslateUi(self, CADASTRO):
        _translate = QtCore.QCoreApplication.translate
        CADASTRO.setWindowTitle(_translate("CADASTRO", "MainWindow"))
        self.label.setText(_translate("CADASTRO", "Nome"))
        self.label_3.setText(_translate("CADASTRO", "CPF:"))
        self.label_2.setText(_translate("CADASTRO", "Sobrenome"))
        self.cadastrar.setText(_translate("CADASTRO", "Cadastrar"))
        self.label_8.setText(_translate("CADASTRO", "CADASTRO"))
        self.label_5.setText(_translate("CADASTRO", "CPf:"))
        self.label_4.setText(_translate("CADASTRO", "Nome"))
        self.label_6.setText(_translate("CADASTRO", "Sobrenome"))
        self.btn_buscar.setText(_translate("CADASTRO", "Buscar"))
        self.label_7.setText(_translate("CADASTRO", "CPF:"))
        self.label_9.setText(_translate("CADASTRO", "BUSCAR PESSOA"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CADASTRO = QtWidgets.QMainWindow()
    ui = Ui_CADASTRO()
    ui.setupUi(CADASTRO)
    CADASTRO.show()
    sys.exit(app.exec_())
